name : marapendi
channels:
  - anaconda
  - conda-forge
dependencies :
  - python>=3.10
  - pandas
  - pandoc
  - pip
  - cantera
  - pip :
    - cython
    - xarray
    - pytest
    - pytest-cov
    - sphinx>=7.0
    - notebook
    - pylint
    - sphinx-autoapi
    - nbsphinx
    - pydata-sphinx-theme>=0.15
    - sphinx-copybutton
    - sphinx-design
    - sphinx-autodoc-typehints
    - scipy
    - matplotlib
