name : marapendi
channels:
  - anaconda
  - conda-forge
dependencies :
  - python>=3.10
  - pandas
  - pandoc
  - pip
  - cantera
  - pip :
    - cython
    - pytest
    - pytest-cov
    - sphinx
    - notebook
    - pylint
    - sphinx-autoapi
    - nbsphinx
    - scipy
    - matplotlib
